# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a node image with version 20.x for building
FROM node:20-alpine AS builder

# Create app directory
WORKDIR /app

# Copy all files first
COPY . .

# Install all dependencies including devDependencies
RUN npm ci

# Build the application
RUN npm run build

# Production stage
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files and install only production dependencies
COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts

# Copy built files from builder
COPY --from=builder /app/dist ./dist

# Set environment variables
ENV NODE_ENV=production
ENV PORT=3000

# Expose the port the app runs on
EXPOSE 3000

# Command to run the executable
CMD ["node", "dist/src/index.js"]
